In [ ]:
Q1 – Data Merging and Lookup Operations with Pandas

In [1]:
import pandas as pd

In [ ]:
TASK 1: Data Preparation and Missing Value Handling

In [ ]:
Step 1: Create DataFrames

In [3]:
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}

enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}

scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}

students = pd.DataFrame(students_data)
enrollments = pd.DataFrame(enrollments_data)
scores = pd.DataFrame(scores_data)

print("Original Students DataFrame")
display(students)

Original Students DataFrame

   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi

In [ ]:
Step 2: Null Value Analysis

In [4]:
print("Null Value Analysis")

for column in students.columns:
    null_count = students[column].isnull().sum()
    percentage = (null_count / len(students)) * 100
    print(f"Column: {column}, Nulls: {null_count} ({percentage:.2f}%)")

Null Value Analysis
Column: student_id, Nulls: 0 (0.00%)
Column: name, Nulls: 1 (14.29%)
Column: email, Nulls: 1 (14.29%)
Column: city, Nulls: 1 (14.29%)

In [ ]:
| Column     | Nulls |
| ---------- | ----- |
| student_id | 0     |
| name       | 1     |
| email      | 1     |
| city       | 1     |

In [ ]:
Step 3: Fill Missing City Values

In [5]:
students['city'] = students['city'].fillna('Unknown')

In [ ]:
Step 4: Drop Rows where Name is Missing

In [6]:
students_clean = students.dropna(subset=['name'])

In [ ]:
Step 5: Display Cleaned DataFrame

In [7]:
print("Cleaned Students DataFrame")
display(students_clean)

Cleaned Students DataFrame

   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

In [ ]:
Final rows = 6 students (student 103 removed).

In [ ]:
TASK 2: Multiple Join Operations

In [ ]:
1️⃣ Inner Join

In [8]:
inner_join = pd.merge(students_clean, enrollments, on='student_id', how='inner')
display(inner_join)

print("Number of students:", len(inner_join))

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10

Number of students: 3

In [ ]:
Result

Rows = 3

Students present:

101 – Alice
102 – Bob
105 – Emma

In [ ]:
Question Answer

Which students are excluded?

Excluded student_ids:

104, 106, 107

Reason:
They do not appear in the enrollments table.

In [ ]:
2️⃣ Left Join

In [9]:
left_join = pd.merge(students_clean, enrollments, on='student_id', how='left')
display(left_join)

print("Total rows:", len(left_join))

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,104,David,None,Mumbai,NaN,NaN
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,NaN,NaN
5,107,Grace,grace@email.com,Delhi,NaN,NaN

Total rows: 6

In [ ]:
Result

Rows = 6

Students with NULL course_name
104, 106, 107

Reason:
They exist in students table but not in enrollments.

In [ ]:
3️⃣ Right Join

In [10]:
right_join = pd.merge(students_clean, enrollments, on='student_id', how='right')
display(right_join)

print("Total rows:", len(right_join))

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,108,NaN,NaN,NaN,AI,2024-02-15
5,109,NaN,NaN,NaN,Python,2024-03-01

Total rows: 6

In [ ]:
Result

Rows = 6

Student IDs without names
103, 108, 109

Reason:

They appear in enrollments

But not in cleaned students table.

In [ ]:
4️⃣ Full Outer Join

In [11]:
outer_join = pd.merge(students_clean, enrollments, on='student_id', how='outer')
display(outer_join)

print("Total rows:", len(outer_join))

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,104,David,None,Mumbai,NaN,NaN
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
5,106,Frank,frank@email.com,Chennai,NaN,NaN
6,107,Grace,grace@email.com,Delhi,NaN,NaN
7,108,NaN,NaN,NaN,AI,2024-02-15
8,109,NaN,NaN,NaN,Python,2024-03-01

Total rows: 9

In [ ]:
Result

Rows = 9

In [ ]:
Rows where name OR course_name is null

In [12]:
missing_rows = outer_join[
    outer_join['name'].isnull() | outer_join['course_name'].isnull()
]

display(missing_rows)

   student_id   name            email     city course_name enrollment_date
2         103    NaN              NaN      NaN      Python      2024-02-01
3         104  David             None   Mumbai         NaN             NaN
5         106  Frank  frank@email.com  Chennai         NaN             NaN
6         107  Grace  grace@email.com    Delhi         NaN             NaN
7         108    NaN              NaN      NaN          AI      2024-02-15
8         109    NaN              NaN      NaN      Python      2024-03-01

In [ ]:
Merge Source Indicator

In [13]:
outer_indicator = pd.merge(
    students_clean,
    enrollments,
    on='student_id',
    how='outer',
    indicator=True
)

display(outer_indicator)

print(outer_indicator['_merge'].value_counts())

,student_id,name,email,city,course_name,enrollment_date,_merge
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15,both
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20,both
2,103,NaN,NaN,NaN,Python,2024-02-01,right_only
3,104,David,None,Mumbai,NaN,NaN,left_only
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10,both
5,106,Frank,frank@email.com,Chennai,NaN,NaN,left_only
6,107,Grace,grace@email.com,Delhi,NaN,NaN,left_only
7,108,NaN,NaN,NaN,AI,2024-02-15,right_only
8,109,NaN,NaN,NaN,Python,2024-03-01,right_only

_merge
left_only     3
right_only    3
both          3
Name: count, dtype: int64

In [ ]:
Expected distribution:

| Source     | Meaning          |
| ---------- | ---------------- |
| both       | in both tables   |
| left_only  | only students    |
| right_only | only enrollments |

Example counts:
both          3
left_only     3
right_only    3

In [ ]:
TASK 3: Lookup Operation and Automation

In [ ]:
1️⃣ Lookup using Dictionary + map()

In [ ]:
Create Dictionary

In [14]:
score_dict = dict(zip(scores['student_id'], scores['exam_score']))
print(score_dict)

{101: 85, 102: 92, 104: 78, 105: 88, 106: 95}

In [ ]:
Example:

{101:85, 102:92, 104:78, 105:88, 106:95}

In [ ]:
Add Scores using map()

In [15]:
students_clean['exam_score'] = students_clean['student_id'].map(score_dict)

display(students_clean[['student_id','name','exam_score']])

/tmp/ipykernel_463/1186645979.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students_clean['exam_score'] = students_clean['student_id'].map(score_dict)

   student_id   name  exam_score
0         101  Alice        85.0
1         102    Bob        92.0
3         104  David        78.0
4         105   Emma        88.0
5         106  Frank        95.0
6         107  Grace         NaN

In [ ]:
Output:

| student_id | name  | exam_score |
| ---------- | ----- | ---------- |
| 101        | Alice | 85         |
| 102        | Bob   | 92         |
| 104        | David | 78         |
| 105        | Emma  | 88         |
| 106        | Frank | 95         |
| 107        | Grace | NaN        |

Grace has NaN because no score exists.

In [ ]:
2️⃣ Same Operation using Merge

In [18]:
print(merge_scores.columns)

Index(['student_id', 'name', 'email', 'city', 'exam_score_x', 'exam_score_y'], dtype='object')

In [19]:
display(merge_scores[['student_id','name','exam_score_y']])

   student_id   name  exam_score_y
0         101  Alice          85.0
1         102    Bob          92.0
2         104  David          78.0
3         105   Emma          88.0
4         106  Frank          95.0
5         107  Grace           NaN

In [22]:
students_clean = students_clean.drop(columns=['exam_score'], errors='ignore')

In [23]:
merge_scores = pd.merge(
    students_clean,
    scores,
    on='student_id',
    how='left'
)

display(merge_scores[['student_id','name','exam_score']])

   student_id   name  exam_score
0         101  Alice        85.0
1         102    Bob        92.0
2         104  David        78.0
3         105   Emma        88.0
4         106  Frank        95.0
5         107  Grace         NaN

In [ ]:
Why map() is More Efficient

Lookup using map() is faster because:

1️⃣ It performs direct dictionary lookups (O(1)).
2️⃣ No need to create a new DataFrame structure.
3️⃣ Lower memory usage.
4️⃣ Best when adding a single column from key-value mapping.

merge() is better when:

Joining multiple columns

Combining multiple tables

In [ ]:
3️⃣ Automation Function

In [24]:
def auto_merge(df1, df2, join_type, key_column):

    merged_df = pd.merge(df1, df2, on=key_column, how=join_type)

    result = {
        'result_df': merged_df,
        'row_count': len(merged_df),
        'join_type': join_type
    }

    return result

In [ ]:
Test Function

In [ ]:
Test 1 – Inner Join

In [25]:
test1 = auto_merge(students_clean, enrollments, 'inner', 'student_id')

print("Join Type:", test1['join_type'])
print("Rows in Result:", test1['row_count'])

display(test1['result_df'].head())

Join Type: inner
Rows in Result: 3

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10

In [ ]:
Test 2 – Left Join

In [26]:
test2 = auto_merge(students_clean, enrollments, 'left', 'student_id')

print("Join Type:", test2['join_type'])
print("Rows in Result:", test2['row_count'])

display(test2['result_df'].head())

Join Type: left
Rows in Result: 6

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,104,David,None,Mumbai,NaN,NaN
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,NaN,NaN

In [ ]:
Student Name: Ragul E

Notebook Link: https://github.com/R01ty/Data-Merging-and-Lookup-Operations-with-Pandas.git

All Tasks Completed: Yes

Additional Notes:
This assignment helped understand different types of joins in pandas and when to use map vs merge for lookup operations.